Handle SearchOrganizer and SearchVolunteer pages
UEH-Squad/VMS pull request #190
Opened 2021-12-29 14:39 UTC by hoanguyennph

2021-12-30 02:59 UTC, hoaitran308 commented
@hoanguyennph sao không re-use component search org result mà lại tạo cái mới làm gì em. Anh thấy Lâm có xử lý hiển thị kết quả tìm kiếm là org/user luôn rồi mà.

2021-12-30 03:03 UTC, hoanguyennph commented
> @hoanguyennph sao không re-use component search org result mà lại tạo cái mới làm gì em. Anh thấy Lâm có xử lý hiển thị kết quả tìm kiếm là org/user luôn rồi mà.

Em quên mất ko để ý phần đó mà em lỡ làm mới rồi nên để vậy không biết BE có mất công làm lại nhiều không ạ.

2021-12-30 17:51 UTC, hoaitran308 approved these changes
It looks good now!

2022-01-01 17:37 UTC, hoaitran308 requested changes
@hoanguyennph có gì em fix lại phần UI mà Hiếu nói nhé!

2022-01-02 12:44 UTC, npthieu commented
@hoaitran308 Hòa fix UI với get lasted code rồi nha.

2022-01-03 14:51 UTC, hoaitran308 approved these changes
Looks god now!

2022-01-03 15:01 UTC, merged